version: '3'
services:
  api:
    image: sha256:7a88941a90c35be7be1a5dad1369d400f90eaf5056fe1cf7b1d62577dcf34574
    ports:
      - "8080"
    deploy:
      replicas: 2

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=rinhabackend
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=123456

  nginx:
    image: nginx:latest
    ports:
      - "9999:80"
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
