version: '3.5'

services:
  api1:
    image: sha256:f0203eb4b416709dff310c1d48bc166fbb246b98aaa284680c06e28c49a0ae94
    hostname: api1
    ports:
      - "8080:8080"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
    ports:
      - "9999:9999"
    networks:
      - app-network

  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./create-db.sql:/docker-entrypoint-initdb.d/create_database.sql
    networks:
      - app-network
volumes:
  postgres:

networks:
  app-network: