spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 10000
      connection-timeout: 30000
      max-lifetime: 1800000

---
spring:
  config:
    activate:
      on-profile: 'local'
  datasource:
    url: jdbc:h2:mem:backend-challenge-23;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 10000
      connection-timeout: 30000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: ERROR
    com.soave.backend_performance_challenge: DEBUG

---
spring:
  config:
    activate:
      on-profile: '!local'
  datasource:
    url: jdbc:postgresql://postgres:5432/backend-battle-23
    username: root
    password: root
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 10000
      connection-timeout: 30000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

logging:
  level:
    root: ERROR
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF