spring:
  cache:
    type: simple
  datasource:
    url: jdbc:postgresql://db:5432/rinhabackend
    username: rinha
    password: 123456
    driver-class-name: org.postgresql.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    root: INFO
    org.hibernate.sql: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
    org.springframework.jdbc.core.JdbcTemplate: ERROR
---